"""CLI entry point.

Usage:
    python main.py "https://www.youtube.com/watch?v=..." \
        --num-clips 3 --aspect-ratio 9:16
"""
import argparse
import json
import sys
import os

from shorts_generator import generate_shorts
from shorts_generator.llm import get_trending_videos

def parse_legacy_metadata_txt(txt_path: str) -> dict:
    """Best-effort parser for legacy human-readable text meta files."""
    res = {"title": "", "description": ""}
    if not os.path.exists(txt_path):
        return res
    try:
        with open(txt_path, 'r', encoding='utf-8') as f:
            content = f.read()
        import re
        # Match text following [JUDUL VIDEO] until two newlines
        m_title = re.search(r"\[JUDUL VIDEO\]\n+(.*?)(?:\n\n|\n💬|\n---)", content, re.DOTALL)
        if m_title:
            res["title"] = m_title.group(1).strip()
        
        m_desc = re.search(r"\[CAPTION / DESKRIPSI VIDEO\]\n+(.*?)(?:\n\n|\n🪝|\n---)", content, re.DOTALL)
        if m_desc:
            res["description"] = m_desc.group(1).strip()
    except Exception:
        pass
    return res

def perform_single_upload(video_path: str, privacy: str):
    """Locates companion assets and launches the uploader utility."""
    from shorts_generator.uploader import upload_video_to_youtube
    import os
    
    base = os.path.splitext(video_path)[0]
    json_path = base + "_metadata.json"
    txt_path = base + ".txt"
    thumb_path = base + "_thumbnail.jpg"
    
    title = os.path.basename(base).replace("_", " ").title()
    description = "Generated by AI Shorts Generator."
    
    # Load Title/Desc from Sidecars
    if os.path.exists(json_path):
        try:
            with open(json_path, 'r', encoding='utf-8') as jf:
                data = json.load(jf)
                title = data.get("title") or title
                description = data.get("description") or description
            print(f"[cli] Loaded metadata from JSON sidecar: {os.path.basename(json_path)}", flush=True)
        except Exception:
            pass
    elif os.path.exists(txt_path):
        legacy = parse_legacy_metadata_txt(txt_path)
        if legacy.get("title"):
            title = legacy["title"]
        if legacy.get("description"):
            description = legacy["description"]
        print(f"[cli] Derived metadata from legacy .txt sidecar: {os.path.basename(txt_path)}", flush=True)

    actual_thumb = thumb_path if os.path.exists(thumb_path) else None
    if actual_thumb:
        print(f"[cli] Found custom thumbnail attachment: {os.path.basename(actual_thumb)}", flush=True)
    else:
        print(f"[cli] Note: No companion thumbnail file found, will use YouTube auto-select.", flush=True)

    print(f"\n🚀 Preparing Upload: {os.path.basename(video_path)}")
    print(f"📌 Title: {title}")
    
    try:
        upload_video_to_youtube(
            video_path=video_path,
            title=title,
            description=description,
            privacy=privacy,
            thumbnail_path=actual_thumb
        )
    except Exception as e:
        if str(e) == "DAILY_QUOTA_HIT":
            print("\n❌ HALT: Daily YouTube Quota Limit Reached.", flush=True)
            return False
        else:
            print(f"\n❌ FAILED UPLOADING {os.path.basename(video_path)}: {e}", flush=True)
            return False
    return True



def main() -> int:
    parser = argparse.ArgumentParser(description="AI YouTube Shorts Generator")
    parser.add_argument("url", nargs="?", help="YouTube video URL")
    parser.add_argument("--num-clips", type=int, default=3, help="How many shorts to render (default: 3, use 0 for all found)")
    parser.add_argument("--aspect-ratio", default="9:16", help="Output aspect ratio (default: 9:16)")
    parser.add_argument("--format", default="1080", help="Source download resolution: 360 / 480 / 720 / 1080 (default: 1080)")
    parser.add_argument("--language", default=None, help="Force Whisper language code, e.g. 'en' (default: auto-detect)")
    parser.add_argument("--output-json", default=None, help="Write the full result JSON to this path")
    parser.add_argument("--interactive", action="store_true", help="Pause and choose which candidates to render")
    parser.add_argument("--trends", action="store_true", help="Discover trending podcasts and choose one to process")
    
    # New Upload Flags
    parser.add_argument("--upload", action="store_true", help="Prompt to upload rendered clips to YouTube automatically")
    parser.add_argument("--privacy", default="private", choices=["public", "private", "unlisted"], help="Upload privacy visibility (default: private)")
    parser.add_argument("--upload-only", type=str, default=None, help="Directly upload an already rendered .mp4 to YouTube standalone")
    
    args = parser.parse_args()

    import os
    
    # 0. Standalone Upload Path (Bypasses Pipeline)
    if args.upload_only:
        if not os.path.exists(args.upload_only):
            print(f"Error: Target video path not found: {args.upload_only}", flush=True)
            return 1
        perform_single_upload(args.upload_only, privacy=args.privacy)
        return 0

    target_url = args.url

    # Dynamic Selection flow via --trends
    if args.trends:
        try:
            videos = get_trending_videos()
            if not videos:
                print("\n[trends] No trending podcasts found or Gemini returned empty. Aborting.", flush=True)
                return 1
            
            print("\n" + "🚀" * 25)
            print("       DISCOVER TRENDING PODCASTS")
            print("🚀" * 25)
            for idx, v in enumerate(videos, 1):
                date_str = v.get('date', 'Unknown Date')
                print(f"[{idx:2}] 📅 {date_str} | 🎙️ {v.get('title')}")
            
            print("\n👉 Enter the number you want to process")
            print("👉 Or press Ctrl+C to exit")
            
            choice = input("\nChoice > ").strip()
            if not choice:
                print("[trends] No selection made. Exiting.", flush=True)
                return 0
            
            sel_idx = int(choice) - 1
            if 0 <= sel_idx < len(videos):
                vid_info = videos[sel_idx]
                print(f"\n[trends] Authenticating exact source URL for '{vid_info.get('title')}'...", flush=True)
                
                from shorts_generator.downloader import lookup_youtube_url_by_title
                verified_url = lookup_youtube_url_by_title(vid_info.get('title'))
                
                if verified_url:
                    target_url = verified_url
                    print(f"[trends] Locked authenticated URL: {target_url}", flush=True)
                else:
                    # Revert to Gemini supplied URL fallback
                    target_url = vid_info.get("url")
                    print(f"[trends] Using direct fallback URL: {target_url}", flush=True)
            else:
                print("[trends] Invalid choice number. Exiting.", flush=True)
                return 1
        except KeyboardInterrupt:
            print("\n[trends] Cancelled. Exiting.", flush=True)
            return 0
        except ValueError:
            print("[trends] Invalid input format. Exiting.", flush=True)
            return 1

    if not target_url:
        parser.error("A valid YouTube URL is required, or use --trends to pick one.")

    try:
        result = generate_shorts(
            youtube_url=target_url,
            num_clips=args.num_clips,
            aspect_ratio=args.aspect_ratio,
            download_format=args.format,
            language=args.language,
            interactive=args.interactive,
        )
    except KeyboardInterrupt:
        print("\n\n[pipeline] Aborted by user (Ctrl+C). Exiting.", file=sys.stderr, flush=True)
        return 0
    except Exception as e:
        print(f"\nFAILED: {e}", file=sys.stderr)
        return 1

    print("\n" + "=" * 72)
    print(f"Mode:          local")
    print(f"Source video:  {result['source_video_url']}")
    print(f"Highlights:    {len(result['highlights'])} candidates → kept top {len(result['shorts'])}")
    print("=" * 72)
    for i, s in enumerate(result["shorts"], 1):
        print(f"\n#{i}  score={s.get('score')}  {s.get('start_time'):.1f}s → {s.get('end_time'):.1f}s")
        print(f"     title:  {s.get('title')}")
        print(f"     hook:   {s.get('hook_sentence')}")
        if s.get("clip_url"):
            print(f"     clip:   {s['clip_url']}")
        else:
            print(f"     clip:   FAILED ({s.get('error')})")

    if args.output_json:
        with open(args.output_json, "w") as f:
            json.dump(result, f, indent=2)
        print(f"\nFull JSON written to {args.output_json}")

    # FINAL STEP: Optional YouTube Upload Trigger
    if args.upload:
        rendered = [s for s in result["shorts"] if s.get("clip_url")]
        if not rendered:
            print("\n[uploader] No successfully rendered clips to upload. Skipping phase.", flush=True)
            return 0
            
        print("\n" + "🔥" * 25)
        print("       SELECT RENDERED CLIPS TO UPLOAD")
        print("🔥" * 25)
        for idx, s in enumerate(rendered, 1):
            print(f"[{idx:2}] 🎬 {s.get('title')} ({os.path.basename(s['clip_url'])})")
            
        print("\n👉 Enter numbers to upload (e.g. '1 2'), or type 'all'")
        print(f"👉 Or press [ENTER] to exit and keep local only")
        
        try:
            import re
            u_choice = input("\nUpload Choice > ").strip().lower()
            if not u_choice:
                print("[uploader] Upload phase skipped. Have a great day!", flush=True)
                return 0
                
            target_uploads = []
            if u_choice == "all":
                target_uploads = rendered
            else:
                toks = re.split(r'[,\s]+', u_choice)
                inds = [int(t) - 1 for t in toks if t.isdigit()]
                target_uploads = [rendered[i] for i in inds if 0 <= i < len(rendered)]
                
            if not target_uploads:
                print("[uploader] No valid choices selected. Exiting.", flush=True)
                return 0
                
            print(f"\n[uploader] Queuing {len(target_uploads)} video uploads to YouTube...\n", flush=True)
            
            for target_clip in target_uploads:
                path = target_clip["clip_url"]
                success = perform_single_upload(path, privacy=args.privacy)
                if not success:
                    # If quota hit or fail, abort the remainder batch
                    print("[uploader] Aborting remaining uploads due to batch failure.", flush=True)
                    break
                    
        except KeyboardInterrupt:
            print("\n[uploader] Cancelled upload trigger.", flush=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
